name: flake8 linting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
    flake8:
    
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get install -y python3-pip
            - run: pip3 install --break-system-packages --upgrade pip3
            - run: pip3 install --break-system-packages flake8
            - name: Lint with flake8
              run: flake8
