name: flake8 linting

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
    flake8:
    
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt-get install -y python-pip
            - run: pip install --break-system-packages --upgrade pip
            - run: pip install --break-system-packages flake8
            - name: Lint with flake8
              run: flake8
